<?php

namespace ParkBundle\Entity;

/**
 * ComputerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComputerRepository extends \Doctrine\ORM\EntityRepository
{
}
