<?php

namespace ParkBundle\Entity;

/**
 * IpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getUnaffectedIps()
    {
        return $this
            ->createQueryBuilder('i')
            ->andWhere('i.computer IS NULL');
    }
}
