cavavin:
    resource: "@CavavinBundle/Controller/"
    type:     annotation
    prefix:   /

park:
    resource: "@ParkBundle/Resources/config/routing.yml"
#    type:     annotation
    prefix:   /park/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
