<?php

namespace CavavinBundle\Entity;

/**
 * VinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VinsRepository extends \Doctrine\ORM\EntityRepository
{
}
